[package]
name = "libcore"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.1.1", features = ["rlp"] }
alloy-rlp = "0.3.12"
clap = { version = "4.5.53", features = ["derive"] }

light-poseidon = "0.4.0"
ark-bn254 = "0.5.0"
ark-ff = "0.5.0"
thiserror = "2.0.17"
anyhow = "1.0.100"
rand = "0.9.2"
reqwest = "0.12.24"
worm-witness-gens = { git = "https://github.com/worm-privacy/witness" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
